// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCey1lLqsSyFRuoKdKGG9JzSxtgLiAcniY',
    appId: '1:41082310429:web:8c22603e0b50d082f99bf4',
    messagingSenderId: '41082310429',
    projectId: 'nutur-ngaji',
    authDomain: 'nutur-ngaji.firebaseapp.com',
    storageBucket: 'nutur-ngaji.appspot.com',
    measurementId: 'G-CH16LS76LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhhSyVBaQhSmc5MqtkjXNZTBNjrj3bYyY',
    appId: '1:41082310429:android:6396e0cc4b4eb127f99bf4',
    messagingSenderId: '41082310429',
    projectId: 'nutur-ngaji',
    storageBucket: 'nutur-ngaji.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ST4B13wbrtRDm5kw7L2wu97PT1sgneA',
    appId: '1:41082310429:ios:27e734b3487f6014f99bf4',
    messagingSenderId: '41082310429',
    projectId: 'nutur-ngaji',
    storageBucket: 'nutur-ngaji.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ST4B13wbrtRDm5kw7L2wu97PT1sgneA',
    appId: '1:41082310429:ios:12d2615ed39f2dbcf99bf4',
    messagingSenderId: '41082310429',
    projectId: 'nutur-ngaji',
    storageBucket: 'nutur-ngaji.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
